# Generated by Django 2.0.6 on 2020-10-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'other')], default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pic',
            field=models.ImageField(default='0.jpg', upload_to='pic/'),
        ),
    ]
